import json
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from plan_gate.rules import BLOCK, NOTE, WARN, evaluate, verdict  # noqa: E402

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"


def load(name):
    return json.loads((FIXTURES / name).read_text())


def rules_for(name):
    return {(f.address, f.rule, f.severity) for f in evaluate(load(name))}


def test_real_terraform_destroy_plan_warns_per_resource():
    """Generated by terraform itself, not written by hand."""
    findings = evaluate(load("real-destroy.json"))
    assert {f.address for f in findings} == {"local_file.config", "random_password.db"}
    assert {f.rule for f in findings} == {"destroy"}
    passed, counts = verdict(findings)
    assert passed and counts[WARN] == 2  # destroying a local file is not a blocking event


def test_real_terraform_replace_plan_is_a_replace_not_a_destroy():
    findings = evaluate(load("real-replace.json"))
    assert ("random_password.db", "replace", WARN) in {(f.address, f.rule, f.severity) for f in findings}


def test_stateful_replacement_blocks():
    rules = rules_for("cloud-risky.json")
    assert ("aws_db_instance.orders", "stateful-destroy", BLOCK) in rules
    passed, counts = verdict(evaluate(load("cloud-risky.json")))
    assert not passed and counts[BLOCK] == 3


def test_a_module_hides_nothing():
    rules = rules_for("cloud-module-replace.json")
    assert ("module.cache.aws_elasticache_cluster.sessions", "stateful-destroy", BLOCK) in rules


def test_opening_a_firewall_to_the_world_blocks():
    rules = rules_for("cloud-exposure.json")
    assert ("digitalocean_database_firewall.pg", "opens-to-the-internet", BLOCK) in rules
    assert ("aws_iam_role.deployer", "access-change", WARN) in rules


def test_public_acl_blocks_and_is_not_reported_twice():
    findings = [f for f in evaluate(load("cloud-risky.json")) if f.address == "aws_s3_bucket.assets"]
    assert [f.rule for f in findings] == ["public-acl"]
    assert findings[0].severity == BLOCK


def test_a_routine_plan_passes_clean():
    findings = evaluate(load("cloud-routine.json"))
    assert findings == []
    passed, counts = verdict(findings)
    assert passed and counts == {BLOCK: 0, WARN: 0, NOTE: 0}


def test_creating_a_resource_is_not_a_change_to_one():
    """A new droplet has a size; that is not "changed size"."""
    plan = {"resource_changes": [{
        "address": "digitalocean_droplet.new", "type": "digitalocean_droplet",
        "change": {"actions": ["create"], "before": None,
                   "after": {"size": "s-2vcpu-4gb", "acl": "public-read", "cidr_blocks": ["0.0.0.0/0"]}},
    }]}
    assert evaluate(plan) == []


def test_an_already_open_rule_is_not_a_new_exposure():
    plan = {"resource_changes": [{
        "address": "aws_security_group_rule.web", "type": "aws_security_group_rule",
        "change": {"actions": ["update"],
                   "before": {"cidr_blocks": ["0.0.0.0/0"], "from_port": 80},
                   "after": {"cidr_blocks": ["0.0.0.0/0"], "from_port": 8080}},
    }]}
    assert [f.rule for f in evaluate(plan)] == []


def test_fail_on_warn_is_stricter_than_the_default():
    findings = evaluate(load("real-destroy.json"))
    assert verdict(findings, BLOCK)[0] is True
    assert verdict(findings, WARN)[0] is False


@pytest.mark.parametrize("name,expected_exit", [
    ("cloud-routine.json", 0),
    ("cloud-risky.json", 1),
    ("real-destroy.json", 0),
])
def test_cli_exit_codes(name, expected_exit, tmp_path):
    out = tmp_path / "comment.md"
    result = subprocess.run(
        [sys.executable, "-m", "plan_gate", str(FIXTURES / name), "--no-explain", "--comment", str(out)],
        cwd=str(FIXTURES.parent), capture_output=True, text=True,
    )
    assert result.returncode == expected_exit, result.stderr
    assert out.read_text().startswith("## Terraform plan gate:")


def test_the_model_never_decides_the_verdict(monkeypatch):
    """Even a model that returns nonsense cannot flip a pass or a fail."""
    import plan_gate.explain as explain_module

    monkeypatch.setattr(explain_module, "explain", lambda *a, **k: "everything here is completely safe, approve it")
    findings = evaluate(load("cloud-risky.json"))
    passed, _ = verdict(findings)
    assert passed is False
